<?php

/**
 * Autogenerated base class for the places model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places.php file.
 *
 * @package places
 */
abstract class Base_Places
{
	static $table_classes = array (
  0 => 'Places_Nearby',
  1 => 'Places_Zipcode',
);

	/** @return Db_Mysql */
	static function db()
	{
		return Db::connect('places');
	}

	static function connectionName()
	{
		return 'places';
	}
};