<?php

/**
 * Autogenerated base class representing forum rows
 * in the streams database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Streams_Forum.php file.
 *
 * @package streams
 *
 * @property int $publisher_id
 * @property string $name
 * @property string $time_created
 * @property string $title
 */
abstract class Base_Streams_Forum extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'publisher_id',
			  1 => 'name',
			)
		);
	}

	static function db()
	{
		return Db::connect('streams');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('streams');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'forum';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('streams');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'streams';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Streams_Forum';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Streams_Forum';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Streams_Forum';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Streams_Forum';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Streams_Forum';
		return $q;
	}
	
	function beforeSet_publisher_id($value)
	{
		if ($value instanceof Db_Expression) return array('publisher_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to streams_forum.publisher_id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to streams_forum.publisher_id');
		return array('publisher_id', $value);			
	}

	function beforeSet_name($value)
	{
		if ($value instanceof Db_Expression) return array('name', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to streams_forum.name');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to streams_forum.name');
		return array('name', $value);			
	}

	function beforeSet_title($value)
	{
		if ($value instanceof Db_Expression) return array('title', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to streams_forum.title');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to streams_forum.title');
		return array('title', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function beforeSave($value)
	{
		if (!$this->retrieved) {
			foreach (array('publisher_id') as $name) {
				if (!isset($value[$name]))
					throw new Exception("The field streams_forum.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
			}
		}
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('publisher_id', 'name', 'time_created', 'title');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};