<?php

/**
 * Autogenerated base class representing notification rows
 * in the streams database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Streams_Notification.php file.
 *
 * @package streams
 *
 * @property string $time_created
 * @property string $time_sent
 * @property int $for_user_id
 * @property int $publisher_id
 * @property string $stream_name
 * @property string $time_viewed
 * @property string $time_read
 * @property string $comment
 */
abstract class Base_Streams_Notification extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			)
		);
	}

	static function db()
	{
		return Db::connect('streams');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('streams');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'notification';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('streams');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'streams';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Streams_Notification';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Streams_Notification';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Streams_Notification';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Streams_Notification';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Streams_Notification';
		return $q;
	}
	
	function beforeSet_time_sent($value)
	{
       if ($value instanceof Db_Expression) return array('time_sent', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to streams_notification.time_sent");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('time_sent', $value);			
	}

	function beforeSet_for_user_id($value)
	{
		if ($value instanceof Db_Expression) return array('for_user_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to streams_notification.for_user_id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to streams_notification.for_user_id');
		return array('for_user_id', $value);			
	}

	function beforeSet_publisher_id($value)
	{
		if ($value instanceof Db_Expression) return array('publisher_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to streams_notification.publisher_id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to streams_notification.publisher_id');
		return array('publisher_id', $value);			
	}

	function beforeSet_stream_name($value)
	{
		if ($value instanceof Db_Expression) return array('stream_name', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to streams_notification.stream_name');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to streams_notification.stream_name');
		return array('stream_name', $value);			
	}

	function beforeSet_time_viewed($value)
	{
       if (!isset($value)) return array('time_viewed', $value);
		if ($value instanceof Db_Expression) return array('time_viewed', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to streams_notification.time_viewed");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('time_viewed', $value);			
	}

	function beforeSet_time_read($value)
	{
       if (!isset($value)) return array('time_read', $value);
		if ($value instanceof Db_Expression) return array('time_read', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to streams_notification.time_read");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('time_read', $value);			
	}

	function beforeSet_comment($value)
	{
		if ($value instanceof Db_Expression) return array('comment', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to streams_notification.comment');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to streams_notification.comment');
		return array('comment', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function beforeSave($value)
	{
		if (!$this->retrieved) {
			foreach (array('for_user_id','publisher_id') as $name) {
				if (!isset($value[$name]))
					throw new Exception("The field streams_notification.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
			}
		}
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('time_created', 'time_sent', 'for_user_id', 'publisher_id', 'stream_name', 'time_viewed', 'time_read', 'comment');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};