<?php

/**
 * Autogenerated base class for the items model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Items.php file.
 *
 * @package items
 */
abstract class Base_Items
{
	static $table_classes = array (
  0 => 'Items_Attribute',
  1 => 'Items_Category',
  2 => 'Items_Endorsement',
  3 => 'Items_Interest',
  4 => 'Items_Item',
  5 => 'Items_ItemDay',
  6 => 'Items_Share',
  7 => 'Items_Tag',
  8 => 'Items_User',
  9 => 'Items_UserDay',
);

	/** @return Db_Mysql */
	static function db()
	{
		return Db::connect('items');
	}

	static function connectionName()
	{
		return 'items';
	}
};