<?php

/**
 * Autogenerated base class for the users model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Users.php file.
 *
 * @package users
 */
abstract class Base_Users
{
	static $table_classes = array (
  0 => 'Users_AppUser',
  1 => 'Users_Contact',
  2 => 'Users_Email',
  3 => 'Users_Mobile',
  4 => 'Users_User',
);

	/** @return Db_Mysql */
	static function db()
	{
		return Db::connect('users');
	}

	static function connectionName()
	{
		return 'users';
	}
};