<h1>Thanks for signing up with our site.</h1>

<h2>
	This is an example activation email, generated by views/users/email/activation.php
</h2>

<p>
	Please make your own view for activation emails, and then either set the
	"users"/"activationEmailView" and "users"/"activationEmailSubject" config fields,
	or pass them to the $user->addEmail() function whenever you call it.
</p>

<p>
	Remember to include a link to activate the email, like this:
	http://mysite.com/verify/email<?echo $email->id ?>/<?php echo $email->activation_code ?>
</p>

<p style="margin-top: 100px;">
	And somewhere on the bottom, you'll probably want to place a link to unsubscribe:
	http://mysite.com/unsubscribe/email<?echo $email->id ?>/<?php echo $email->auth_code ?>
</p>
