<?php

/**
 * Autogenerated base class representing app_user rows
 * in the users database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Users_AppUser.php file.
 *
 * @package users
 *
 * @property int $user_id
 * @property mixed $platform
 * @property int $app_id
 * @property string $time_created
 * @property string $time_updated
 * @property string $session_key
 * @property string $session_expires
 * @property mixed $state
 * @property int $platform_uid
 */
abstract class Base_Users_AppUser extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'user_id',
			  1 => 'platform',
			  2 => 'app_id',
			)
		);
	}

	static function db()
	{
		return Db::connect('users');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('users');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'app_user';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('users');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'users';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Users_AppUser';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Users_AppUser';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Users_AppUser';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Users_AppUser';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Users_AppUser';
		return $q;
	}
	
	function beforeSet_user_id($value)
	{
		if ($value instanceof Db_Expression) return array('user_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to users_app_user.user_id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to users_app_user.user_id');
		return array('user_id', $value);			
	}

	function beforeSet_platform($value)
	{
		if ($value instanceof Db_Expression) return array('platform', $value);
		if (!in_array($value, array('native','facebook')))
			throw new Exception('Out-of-range value being assigned to users_app_user.platform');
		return array('platform', $value);			
	}

	function beforeSet_app_id($value)
	{
		if ($value instanceof Db_Expression) return array('app_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to users_app_user.app_id');
		if ($value < -9.2233720368548E+18 or $value > 9223372036854775807)
			throw new Exception('Out-of-range value being assigned to users_app_user.app_id');
		return array('app_id', $value);			
	}

	function beforeSet_time_updated($value)
	{
       if ($value instanceof Db_Expression) return array('time_updated', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to users_app_user.time_updated");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('time_updated', $value);			
	}

	function beforeSet_session_key($value)
	{
		if (!isset($value)) return array('session_key', $value);
		if ($value instanceof Db_Expression) return array('session_key', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to users_app_user.session_key');
		if (strlen($value) > 128)
			throw new Exception('Exceedingly long value being assigned to users_app_user.session_key');
		return array('session_key', $value);			
	}

	function beforeSet_session_expires($value)
	{
		if (!isset($value)) return array('session_expires', $value);
		if ($value instanceof Db_Expression) return array('session_expires', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to users_app_user.session_expires');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to users_app_user.session_expires');
		return array('session_expires', $value);			
	}

	function beforeSet_state($value)
	{
		if ($value instanceof Db_Expression) return array('state', $value);
		if (!in_array($value, array('visited','added','removed')))
			throw new Exception('Out-of-range value being assigned to users_app_user.state');
		return array('state', $value);			
	}

	function beforeSet_platform_uid($value)
	{
		if ($value instanceof Db_Expression) return array('platform_uid', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to users_app_user.platform_uid');
		if ($value < -9.2233720368548E+18 or $value > 9223372036854775807)
			throw new Exception('Out-of-range value being assigned to users_app_user.platform_uid');
		return array('platform_uid', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function beforeSave($value)
	{
		if (!$this->retrieved) {
			foreach (array('user_id','platform','app_id','platform_uid') as $name) {
				if (!isset($value[$name]))
					throw new Exception("The field users_app_user.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
			}
		}		//if ($this->retrieved and !isset($value['time_updated']))
		// convention: we'll have time_updated = time_created if just created.
			$value['time_updated'] = new Db_Expression('CURRENT_TIMESTAMP');			
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('user_id', 'platform', 'app_id', 'time_created', 'time_updated', 'session_key', 'session_expires', 'state', 'platform_uid');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};