<?php

/**
 * Autogenerated base class representing email rows
 * in the users database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Users_Email.php file.
 *
 * @package users
 *
 * @property int $id
 * @property string $address
 * @property string $time_created
 * @property string $time_updated
 * @property int $user_id
 * @property mixed $state
 * @property string $activation_code
 * @property string $activation_code_expires
 * @property string $auth_code
 */
abstract class Base_Users_Email extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'id',
			)
		);
	}

	static function db()
	{
		return Db::connect('users');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('users');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'email';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('users');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'users';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Users_Email';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Users_Email';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Users_Email';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Users_Email';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Users_Email';
		return $q;
	}
	
	function beforeSet_id($value)
	{
		if ($value instanceof Db_Expression) return array('id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to users_email.id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to users_email.id');
		return array('id', $value);			
	}

	function beforeSet_address($value)
	{
		if ($value instanceof Db_Expression) return array('address', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to users_email.address');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to users_email.address');
		return array('address', $value);			
	}

	function beforeSet_time_updated($value)
	{
       if ($value instanceof Db_Expression) return array('time_updated', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to users_email.time_updated");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('time_updated', $value);			
	}

	function beforeSet_user_id($value)
	{
		if ($value instanceof Db_Expression) return array('user_id', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to users_email.user_id');
		if ($value < 0 or $value > 1.844674407371E+19)
			throw new Exception('Out-of-range value being assigned to users_email.user_id');
		return array('user_id', $value);			
	}

	function beforeSet_state($value)
	{
		if ($value instanceof Db_Expression) return array('state', $value);
		if (!in_array($value, array('unverified','active','suspended','unsubscribed')))
			throw new Exception('Out-of-range value being assigned to users_email.state');
		return array('state', $value);			
	}

	function beforeSet_activation_code($value)
	{
		if ($value instanceof Db_Expression) return array('activation_code', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to users_email.activation_code');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to users_email.activation_code');
		return array('activation_code', $value);			
	}

	function beforeSet_activation_code_expires($value)
	{
       if ($value instanceof Db_Expression) return array('activation_code_expires', $value);
		$date = date_parse($value);
       if (!empty($date['errors']))
           throw new Exception("DateTime $value in incorrect format being assigned to users_email.activation_code_expires");
       foreach (array('year', 'month', 'day', 'hour', 'minute', 'second') as $v)
           $$v = $date[$v];
       $value = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $year, $month, $day, $hour, $minute, $second);
		return array('activation_code_expires', $value);			
	}

	function beforeSet_auth_code($value)
	{
		if ($value instanceof Db_Expression) return array('auth_code', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to users_email.auth_code');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to users_email.auth_code');
		return array('auth_code', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function beforeSave($value)
	{
		if (!$this->retrieved) {
			foreach (array('user_id','state') as $name) {
				if (!isset($value[$name]))
					throw new Exception("The field users_email.$name needs a value, because it is NOT NULL, not auto_increment, and lacks a default value.");
			}
		}		//if ($this->retrieved and !isset($value['time_updated']))
		// convention: we'll have time_updated = time_created if just created.
			$value['time_updated'] = new Db_Expression('CURRENT_TIMESTAMP');			
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('id', 'address', 'time_created', 'time_updated', 'user_id', 'state', 'activation_code', 'activation_code_expires', 'auth_code');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};