<?php

/**
 * Autogenerated base class representing photo rows
 * in the items database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Items_Photo.php file.
 *
 * @package items
 *
 * @property string $item_name
 * @property string $src_url
 * @property string $filename
 * @property int $width
 * @property int $height
 */
abstract class Base_Items_Photo extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			  0 => 'item_name',
			)
		);
	}

	static function db()
	{
		return Db::connect('items');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('items');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'photo';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('items');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'items';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Items_Photo';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Items_Photo';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Items_Photo';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Items_Photo';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Items_Photo';
		return $q;
	}
	
	function beforeSet_item_name($value)
	{
		if ($value instanceof Db_Expression) return array('item_name', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to items_photo.item_name');
		if (strlen($value) > 63)
			throw new Exception('Exceedingly long value being assigned to items_photo.item_name');
		return array('item_name', $value);			
	}

	function beforeSet_src_url($value)
	{
		if ($value instanceof Db_Expression) return array('src_url', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to items_photo.src_url');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to items_photo.src_url');
		return array('src_url', $value);			
	}

	function beforeSet_filename($value)
	{
		if ($value instanceof Db_Expression) return array('filename', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to items_photo.filename');
		if (strlen($value) > 255)
			throw new Exception('Exceedingly long value being assigned to items_photo.filename');
		return array('filename', $value);			
	}

	function beforeSet_width($value)
	{
		if (!isset($value)) return array('width', $value);
		if ($value instanceof Db_Expression) return array('width', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to items_photo.width');
		if ($value < 0 or $value > 4294967295)
			throw new Exception('Out-of-range value being assigned to items_photo.width');
		return array('width', $value);			
	}

	function beforeSet_height($value)
	{
		if (!isset($value)) return array('height', $value);
		if ($value instanceof Db_Expression) return array('height', $value);
		if (!is_numeric($value) or floor($value) != $value)
			throw new Exception('Non-integer value being assigned to items_photo.height');
		if ($value < 0 or $value > 4294967295)
			throw new Exception('Out-of-range value being assigned to items_photo.height');
		return array('height', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('item_name', 'src_url', 'filename', 'width', 'height');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};