<?php

/**
 * Autogenerated base class representing nearby rows
 * in the places database.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places_Nearby.php file.
 *
 * @package places
 *
 * @property string $from_zipcode
 * @property float $miles
 * @property string $to_zipcode
 * @property string $time_updated
 */
abstract class Base_Places_Nearby extends Db_Row
{
	function setUp()
	{
		$this->setDb(self::db());
		$this->setTable(self::table());
		$this->setPrimaryKey(
			array (
			)
		);
	}

	static function db()
	{
		return Db::connect('places');
	}

	static function table($with_db_name = true)
	{
		$conn = Db::getConnection('places');
		$prefix = empty($conn['prefix']) ? '' : $conn['prefix'];
		$table_name = $prefix . 'nearby';
		if (!$with_db_name)
			return $table_name;
		$db = Db::connect('places');
		return $db->dbName().'.'.$table_name;
	}
	
	static function connectionName()
	{
		return 'places';
	}

	/** @return Db_Query_Mysql */
	static function select($fields, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->select($fields, self::table().' '.$alias);
		$q->className = 'Places_Nearby';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function update($alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->update(self::table().' '.$alias);
		$q->className = 'Places_Nearby';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function delete($table_using = null, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->delete(self::table().' '.$alias, $table_using);
		$q->className = 'Places_Nearby';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insert($fields = array(), $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insert(self::table().' '.$alias, $fields);
		$q->className = 'Places_Nearby';
		return $q;
	}

	/** @return Db_Query_Mysql */
	static function insertManyAndExecute($records = array(), $chunk_size = 1, $alias = null)
	{
		if (!isset($alias)) $alias = '';
		$q = self::db()->insertManyAndExecute(self::table().' '.$alias, $records, $chunk_size);
		$q->className = 'Places_Nearby';
		return $q;
	}
	
	function beforeSet_from_zipcode($value)
	{
		if ($value instanceof Db_Expression) return array('from_zipcode', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to places_nearby.from_zipcode');
		if (strlen($value) > 10)
			throw new Exception('Exceedingly long value being assigned to places_nearby.from_zipcode');
		return array('from_zipcode', $value);			
	}

	function beforeSet_to_zipcode($value)
	{
		if ($value instanceof Db_Expression) return array('to_zipcode', $value);
		if (!is_string($value))
			throw new Exception('Must pass a string to places_nearby.to_zipcode');
		if (strlen($value) > 10)
			throw new Exception('Exceedingly long value being assigned to places_nearby.to_zipcode');
		return array('to_zipcode', $value);			
	}

	function afterSet($name, $value)
	{
		if (!in_array($name, $this->fieldNames()))
			$this->notModified($name);
		return $value;			
	}

	function fieldNames($table_alias = null, $field_alias_prefix = null)
	{
		$field_names = array('from_zipcode', 'miles', 'to_zipcode', 'time_updated');
		$result = $field_names;
		if (!empty($table_alias)) {
			$temp = array();
			foreach ($result as $field_name)
				$temp[] = $table_alias . '.' . $field_name;
			$result = $temp;
		} 
		if (!empty($field_alias_prefix)) {
			$temp = array();
			reset($field_names);
			foreach ($result as $field_name) {
				$temp[$field_alias_prefix . current($field_names)] = $field_name;
				next($field_names);
			}
			$result = $temp;
		}
		return $result;			
	}
};